### ISSUE TITLE
CLI import not working?

### ISSUE THREAD

**Issue by lawitschka** [onyxbits/Raccoon#16]
I just tried the CLI for importing several apps into my archive. I created a file with the following content
```
https://play.google.com/store/apps/details?id=org.wikipedia
```
and ran the CLI
```
java -d64 -jar raccoon-3.5.jar -u -a ~/Raccoon/archives/default -i app-list.txt
```
but no apps were download nor did it give any output whatsoever. 

Downloading the one app directly with the `-f` switch worked absolutely fine. Do you have any idea, why this is not working?

**Comment by onyxbits** [comment]
Am Freitag, den 10.07.2015, 07:35 -0700 schrieb Moritz Lawitschka:
> I just tried the CLI for importing several apps into my archive. I
> created a file with the following content
> 
> https://play.google.com/store/apps/details?id=org.wikipedia
> 
> and ran the CLI
> 
> java -d64 -jar raccoon-3.5.jar -u -a ~/Raccoon/archives/default -i app-list.txt
> 
> but no apps were download nor did it give any output whatsoever. 
> 
> Downloading the one app directly with the -f switch worked absolutely
> fine. Do you have any idea, why this is not working?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

The -i option is kinda counterintuitive. It does not download anything
at all, only create the archive folders that will be populated the next
time you run Raccoon with the -u parameter.

**Comment by lawitschka** [comment]
Ah right, yep, that was my fault :)

Thank you! :+1:
