### ISSUE TITLE
change Raccoon's data directory does not work

### ISSUE THREAD

**Issue by Micha-Btz** [onyxbits/Raccoon#19]
hi there,

java doesn't take the argument. 
java -Draccoon.homedir=/tmp -jar raccoon-3.5.jar creates always a dir in ~
java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

Debian Sid

any ideas how can i change it?

thanks Micha

**Comment by onyxbits** [comment]
System properties must be given prior to the -jar argument.

Am Donnerstag, den 13.08.2015, 10:11 -0700 schrieb Micha-Btz:

**Comment by Micha-Btz** [comment]
according to the FAQ:

You can change Raccoon's data directory if you are using the java version by specifying the raccoon.homedir property, e.g.:

java -Draccoon.homedir=/tmp -jar raccoon.jar 

if i understand it right, the system properties is prior to the -jar argument. Maybe dedicated to OpenJDK?

**Comment by onyxbits** [comment]
It should be -Draccoon.home=...
The docs are wrong.


Am Donnerstag, den 13.08.2015, 22:13 -0700 schrieb Micha-Btz:

**Comment by Micha-Btz** [comment]
sadly doesn't work

**Comment by libBletchley** [comment]
@Micha-Btz 
Are you sure you used "-Draccoon.home=" and not "-Draccoon.homedir="?
The docs are wrong for 3.5.  I works if you drop the "dir".

**Comment by Micha-Btz** [comment]
@libBletchley 
yes, I'm sure.

> mdomann@sysiphus:~/handy/playstore$ strace java -Draccoon.home=/home/mdomann/handy/playstore/Raccoon/ -jar raccoon-3.5.jar 
execve("/usr/bin/java", ["java", "-Draccoon.home=/home/mdomann/han"..., "-jar", "raccoon-3.5.jar"], [/* 52 vars */]) = 0
brk(NULL)                               = 0x6d5000


and it creates ~/Raccoon anyway. I don't have the knowledge to debug further.

**Comment by libBletchley** [comment]
Sorry for the misinfo.  There does seem to be a bug here.  I've just confirmed that ver. 3.5 creates ~/Raccoon, even when -Draccoon.home= is supplied.  A symbolic link workaround seems to work:

$ mkdir -p "$raccoon_dir_desired"
$ [ -d "$HOME"/Raccoon ] \
  && rsync -va -progress "$HOME"/Raccoon/* "$raccoon_dir_desired"/\
  && rm -rf "$HOME"/Raccoon
$ ln -s "$raccoon_dir_desired" "$HOME"/Raccoon
$ java -Draccoon.home="$raccoon_dir_desired"\
          -Duser.locale="${my_locale:-us}"\
          -jar "$jar_dir"/raccoon-3.5.jar

**Comment by RalfJung** [comment]
Well, the entire point was not to have Raccoon pollute `/home`, so creating a symlink isn't really much of a solution.

**Comment by Micha-Btz** [comment]
old version so close this.
