### ISSUE TITLE
Please provide sources for version 4

### ISSUE THREAD

**Issue by fbis251** [onyxbits/Raccoon#24]
We can help you out by providing pull requests before you upload a final build.

**Comment by onyxbits** [comment]
Sorry for the delay, but I need a bit more time for cleaning up.

Am Sonntag, den 27.12.2015, 06:11 -0800 schrieb Fernando Barillas:

**Comment by sschuberth** [comment]
Any update on this?

**Comment by onyxbits** [comment]
I put v4 in a new repository. It's a complete rewrite, so it's not meaningful to continue this one:

https://github.com/onyxbits/raccoon4
