### ISSUE TITLE
Ubuntu installation instructions

### ISSUE THREAD

**Issue by orschiro** [onyxbits/Raccoon#26]
Dear all, 

Thank you very much for this piece of software!

I would like to use it on my Ubuntu desktop to download an `apk` file for my Fairphone device. 

However, I am too inexperienced to know how to run Raccoon on Ubuntu. 

Could someone assist me?

Thankfully,

~Robert

**Comment by onyxbits** [comment]
Make sure that you have Java installed (check with your package manager
for it). Afterwards, double clicking the raccoon.jar file should do the
trick. If not, Open a terminal, chdir to where the raccoon.jar file is
located and try:

java -jar raccoon-3.5.jar

There really is nothing that needs to be installed.


Am Donnerstag, den 21.01.2016, 01:01 -0800 schrieb Robert Orzanna:

**Comment by orschiro** [comment]
Dear @onyxbits,

Thank you very much!

Maybe you find this pull request useful?

https://github.com/onyxbits/Raccoon/pull/27

Warmly,

~Robert

**Comment by onyxbits** [comment]
I'm about to finalize v4.0, so I don't really want to spend any additional effort on v3.x any more.
