### ISSUE TITLE
Add search by bundle ID (reverse-DNS style name format)

### ISSUE THREAD

**Issue by revoltxs** [onyxbits/Raccoon#29]
Hi.

It would be great to be able to search apps (or directly download it) by entering its bundle ID in the search bar.

Let's take an example.
Suppose one wants to download [`https://play.google.com/store/apps/details?id=com.sonymobile.screenrecording`](https://play.google.com/store/apps/details?id=com.sonymobile.screenrecording).

If you search for Live screen streaming or Sony Mobile Communications, you can go up to the fiftieth search page with no luck. Why ? Because the application itself cannot even be found via the desktop Play Store.
I don't know why, I found this link via Sony's official blog on an announce about Xperia software updates.

The truth is a lot of applications cannot be found the conventional way. But if you can get an app's bundle ID in any fashion, you have at my knowledge 99.5% to find it by directly guessing its desktop Play Store's URL.
If the application is paid, there is no way to download it and even when free, you may fail to find it (it happened to me once, though there was a redirection in my Xperia Z3+'s Sony custom Android that linked to a Play Store, meaning that it wasn't an app from a '2.5th' or third-party source).
I think it might not be an issue that either only concerns not-vanilla OS built-in apps or only touches manufacturer custom Android-dedicated ones as there are rare Nexus-exclusive apps that do need their updates on the Play Store and apparently do have Play Store URL but no way to find them via conventional search ways — neither on the mobile app nor on the desktop Play Store (but it'd be better to get feedback from Nexus tinkerers).

I know little to the Android universe so I cannot say whether this is possible or not, though.

Thanks.

**Edit (feb. 20th, 2016, 11h7 A.M.)** : About this direct download thing… Why not just allow an input of a raw text file containing one app bundle identifier per line that would start download them all, one by one ? Of course, said like that, it's easy as can be. Write it down and get it working is another story. But you get the idea.
I wonder if that could help with pulled apps (such as E.A.'s zzSunset-flagged apps).

**Comment by onyxbits** [comment]
Putting this up as a feature request for v4.
