### ISSUE TITLE
Can't log in (GUI) and cannot update anymore (CLI): GooglePlayException

### ISSUE THREAD

**Issue by matsimon** [onyxbits/Raccoon#34]
I don't know yet where to look further (yet), but I realized that roughly around the moment when Google released the Play Services 9.x shortly after I started into having issues with Raccoon in CLI mode which always. Currently on CLI get the following message when trying to update:

```
com.akdeniz.googleplaycrawler.GooglePlayException: Error=UNKNOWN_ERR
[....]
at de.onyxbits.raccoon.App.main(App.java:83)
````
In GUI mode all I get with a fresh raccon is that it cannot log into the account anymore. I checked that the account(s) in use could indeed still log into web portals of the play store so they should be OK.

The library you are using in raccoon in order to talk to the Play Store doesn't seem to have gotten much love lately so possibly Google made some breaking changes lately.

If I can provide you with additional debug messages I'm happy to help - I'd be interested in hearing if the issue is reproducible other than on my Linux (OpenJDK 8) and Windows (Oracle JRE 8) system I tested on.

**Comment by onyxbits** [comment]
v3.6 should fix the problem.

Am Freitag, den 27.05.2016, 01:45 -0700 schrieb Mathieu Simon:

**Comment by matsimon** [comment]
Thank you very much - I just read your blogpost this day and wanted to say thank you - and those who helped as you mentioned there - for the "Jelly Bean"-style workaround. I know it's likely not the best fix, but I can confirm that for now this works and hope you can focus on your pressing deadlines you have to meet. I'd say it's not worth in keeping this bug open.
