### ISSUE TITLE
Select what device you want to use

### ISSUE THREAD

**Issue by captainepoch** [onyxbits/Raccoon#38]
Hello.

I discovered Raccoon today. When I logged in for the first time, it added a Samsung Galaxy Note 5 as my actual device.

Would it be possible to add an option to use the device you want to into Raccoon?

**Comment by onyxbits** [comment]
Thats the job of DummyDroid and kinda too complex to embed it into
Raccoon.

Am Freitag, den 26.08.2016, 01:42 -0700 schrieb Adolfo Santiago:
