### ISSUE TITLE
Published Code Here Stops at 3.7 Release and New Binary Version on Developer Page with Opt-in Paid Features at 4.2

### ISSUE THREAD

**Issue by xee5ch** [onyxbits/Raccoon#41]
Is part of your move to a freemium and paid feature model mean you will no longer release the free version, currently with JAR builds available on your site at 4.2, going to be mirrored here so we can review the source and help out?  The current version available at the time of this report is 3.7 judging from your last commit to update the version string from 3.6 to 3.7.

I believe you deserve money, but I like to support open developers first.   I for one will donate to you ASAP if you intend to continue releasing the source to the free components.

**Comment by onyxbits** [comment]
I strongly belive in open source software and therefore, the source code for v4.x is just as available as the v3.x one was. Just not in this repository, as v4.x is more or less a complete rewrite:

https://github.com/onyxbits/raccoon4/
