### ISSUE TITLE
feature request - Show App package name in search result, and minimum SDK version if possible

### ISSUE THREAD

**Issue by MKaveh** [onyxbits/Raccoon#44]
- When searching for an app, show app package name (as well as app name, developer name). It can be useful for identifying exact app or apps with similar name.
- Show minimum required Android version (or SDK version) for the current device profile, in the app info. section. so that it's possible to know compatible Android version before downloading the app. (especially when using a generic device profile which sdk version is not known)
- Also display search results in different view (List, Details view: with more info about app,..)

**Comment by onyxbits** [comment]
Wrong repository. The current development branch is here: https://github.com/onyxbits/raccoon4

**Comment by MKaveh** [comment]
Ok, I didn't know that the repository has moved to another location.
I think I used the old link.

2017-04-20 18:58 GMT+04:30 onyxbits <notifications@github.com>:

**Comment by MKaveh** [comment]
I was reffering to the latest version, Raccoon 4.x.

2017-04-22 0:10 GMT+04:30 Thunder T <thundersparkle@gmail.com>:
