### ISSUE TITLE
Raccoon on a headless Ubuntu server

### ISSUE THREAD

**Issue by rehmatworks** [onyxbits/Raccoon#45]
Thanks for your efforts. I attempted to run Raccoon on an Ubuntu server (CLI) and it says 'No profile to connect with.'. Is there a way to set google play credentials? If possible, can you please make it compatible for CLI usage? Thanks in advance.

**Comment by onyxbits** [comment]
This version of Raccoon is no longer supported/in development. Current version is here: https://github.com/onyxbits/raccoon4/
