### ISSUE TITLE
Tiny Request:  Ad the in "numbers" the rating of the app under the gauge.

### ISSUE THREAD

**Issue by mikhoul** [onyxbits/Raccoon#46]
Please Ad the in "numbers" the rating of the app under the gauge directly without the need to hover on the icon to see it, it would be more easy to find new apps with better rating especially when their score is around "4".

Maybe just put it as an option if you think some will not like it.

Thanks for this very useful utility 😺 

Regards :octocat:

**Comment by onyxbits** [comment]
I have plans for redesigning the search result pane. In particular: getting rid of the JButton; drawing everything by hand. 

Feel free to suggest a layout.

**Comment by onyxbits** [comment]
PS: Wrong repository. This is the legacy v3.x version,
