### ISSUE TITLE
No search results for certain GSF IDs

### ISSUE THREAD

**Issue by numbi** [onyxbits/Raccoon#47]
Hi, unfortunately I'm not able to search for apps at certain GSF IDs. The IDs were generated by DummyDroid. When I set up a new account with a random ID, app search works perfectly, but I have to use the correct ID as my phone is giving me parsing errors for some apps. 
With the IDs from DummyDroid there are always "no results", no matter what I'm looking for, in raccoon.
I'm using Windows 7, raccoon-4.1.4.exe, Samsung Galaxy N7100.
Thanks, I really appreciate your work and of course I have purchased a code :)

**Comment by onyxbits** [comment]
Wrong repository, please move this to https://github.com/onyxbits/raccoon4/issues
