### ISSUE TITLE
[Windows 10] Login issue: Bad authorization

### ISSUE THREAD

**Issue by backupandforkacc** [onyxbits/Raccoon#54]
I have tried multiple times to start the login with my gmail credentials, but I fail every time. I guess the project might not be maintained and the newest login procedure from google is not implemented.

Is there any chance to get an apk from the google play store?

**Comment by onyxbits** [comment]
The project is maintained, login works for me without problems.

If you want further assistance, you'll have to open a support ticket via Help|Support (this here is the issue tracker, not the support forum).
